### ISSUE TITLE
Statistics for `delayedAssign` and `force`

### ISSUE THREAD

**Issue by aviralg** [PRL-PRG/R-dyntrace#115]
[delayedAssign](https://stat.ethz.ch/R-manual/R-devel/library/base/html/delayedAssign.html) is a mechanism which lets programmers create promises to take advantage of lazy evaluation in R. The complementary function [force](https://stat.ethz.ch/R-manual/R-devel/library/base/html/force.html) forces a promise.  It would be useful to know how often these are used because any discussion about promises should be backed up with data about its explicit usage by R programmers. Since the tracing collects information about all functions that are called, this might just be a simple search through the database for functions with these names.

**Comment by kondziu** [comment]
This ties in to counting eval as well, so if i provide a method for counting calls to specific functions (or if I count calls to specific functions) would that be sufficient?

E.g. something like this (obviously numbers made up)
```
function.id      called.as               n.called                  perc.called
34343             eval                     10000                     5%
66666             delayedAssign          5000                      2.5%
77777             force                     5000                     2.5
```

**Comment by aviralg** [comment]
I think that would be sufficient.
