### ISSUE TITLE
Tracing entire session

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#16]
Right now the tracer really just works for a single Rdt(...) call. If you make several Rdt calls in a row, they will overwrite each other. Even if you generate two traces from two calls, they can't be concatenaed and analyzed together, because they will have non-unique call ids. Maybe we could have sessions to string Rdt together, so that they could be used and analyzed together. That would make debugging easier. We could also use this to execute stuff incrementally.

**Comment by nohajc** [comment]
One thing I don't like are all the global variables representing the state of a tracer pass. This makes it a mess when we want to control the state to properly overwrite/append. Maybe we could encapsulate the tracer in a class. I realize the interpreter hooks themselves are global, so maybe a singleton makes sense?

You create an instance at the beginning (resetting all the id sequences and stuff) and then you maintain that instance across multiple Rdt calls unless the overwrite flag is set to true, in which case you call reset on the instance.

What we have to think about though, is that some combinations of Rdt options won't be valid. Like if you want to append to the previous trace but you choose a different location and/or format.
