### ISSUE TITLE
Revert to overwrite

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#30]
I think if you were working in non-overwrite mode and then switch settings, we should either revert to overwrite or just switch settings, reset the tracer and start a new "session". The way it ignores any changes in options is just way too annoying.

**Comment by kondziu** [comment]
Does this close the issue? ea518b6ce71aa040ce7184251921948dc1d1cec1

**Comment by nohajc** [comment]
Yes, I forgot to close it.
