### ISSUE TITLE
Gather location and definition information fof built-in functions

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#39]
Right now we get a lot of `NULL`s for locations of both functions and built-ins. We mostly get definitions for functions, but we lack anything like that (at least in the DB) for built-in calls. This makes them a little difficult to recognize in the db. I think right now the problem is that we just pass NULLs to the database without doing anything. Maybe we can get some info about them though?

**Comment by licekto** [comment]
Code in this commit: https://github.com/PRL-PRG/R-dyntrace/commit/9662ae27017b420de2a9dc070ae113c16ce75d34

**Comment by licekto** [comment]
Code in this commit: https://github.com/PRL-PRG/R-dyntrace/commit/9662ae27017b420de2a9dc070ae113c16ce75d34

Location for builtin functions is NULL everytime.
Definition of builtin functions is usually something like "Primitive("if")"
