### ISSUE TITLE
...

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#4]
Analyze triple dot arguments correctly.

**Comment by nohajc** [comment]
Should mostly work now. There's a weird case when you declare a function which takes `...` as its only argument. When calling such a function I'm having trouble retrieving the DOTSXP from environment.

**Comment by nohajc** [comment]
OK, I don't know what I saw yesterday... I tried it again and it works.

**Comment by kondziu** [comment]
I'm reopening this provisionally, I think there are still some problems with how this is handled. There is some ambiguity about promises coming from dot-dots right now, and I think we should fix it. Unless I'm misreading things.

Anyway, if I have:

```
f<-function(x=0,y=0,z=0,v=0)x+y+z+v
g<-function(a,b,...)a+f(z=b, ...)
trace.promises.r(g(a=1, b=2, x=3, v=4))
```

This spits out:

```
=> prom loc(<unknown>) prom(<unknown>=560af683fd28) in(0) from(0)
=> prom loc(<unknown>) prom(expression=560af683fe08) in(0) from(0)
=> func loc(<console>) call(1) fun(g=560af683ec90) arguments(a=560af6842ba8;b=560af6842b38;...=560af6842ac8,560af6842a58)
        => b-in loc(<unknown>) fun(+=560af5b46f70)
        => prom loc(<unknown>) prom(a=560af6842ba8) in(1) from(1)
        <= prom loc(<unknown>) prom(a=560af6842ba8) in(1) from(1)
        => func loc(<console>) call(3) fun(f=560af683e4d0) arguments(x=560af68427b8;y=560af6843528;z=560af6842828;v=560af6842748)
                => b-in loc(<unknown>) fun(+=560af5b46f70)
                => b-in loc(<unknown>) fun(+=560af5b46f70)
                => b-in loc(<unknown>) fun(+=560af5b46f70)
                => prom loc(<unknown>) prom(x=560af68427b8) in(3) from(3)
                => prom loc(<unknown>) prom(<unknown>=560af6842ac8) in(3) from(1)
                <= prom loc(<unknown>) prom(<unknown>=560af6842ac8) in(3) from(1)
                <= prom loc(<unknown>) prom(x=560af68427b8) in(3) from(3)
                => prom loc(<unknown>) prom(y=560af6843528) in(3) from(3)
                <= prom loc(<unknown>) prom(y=560af6843528) in(3) from(3)
                <= b-in loc(<unknown>) fun(+=560af5b46f70)
                => prom loc(<unknown>) prom(z=560af6842828) in(3) from(3)
                => prom loc(<unknown>) prom(b=560af6842b38) in(3) from(1)
                <= prom loc(<unknown>) prom(b=560af6842b38) in(3) from(1)
                <= prom loc(<unknown>) prom(z=560af6842828) in(3) from(3)
                <= b-in loc(<unknown>) fun(+=560af5b46f70)
                => prom loc(<unknown>) prom(v=560af6842748) in(3) from(3)
                => prom loc(<unknown>) prom(<unknown>=560af6842a58) in(3) from(1)
                <= prom loc(<unknown>) prom(<unknown>=560af6842a58) in(3) from(1)
                <= prom loc(<unknown>) prom(v=560af6842748) in(3) from(3)
                <= b-in loc(<unknown>) fun(+=560af5b46f70)
        <= func loc(<console>) call(3) fun(f=560af683e4d0) arguments(x=560af68427b8;y=560af6843528;z=560af6842828;v=560af6842748)
        <= b-in loc(<unknown>) fun(+=560af5b46f70)
<= func loc(<console>) call(1) fun(g=560af683ec90) arguments(a=560af6842ba8;b=560af6842b38;...=560af6842ac8,560af6842a58)
<= prom loc(<unknown>) prom(expression=560af683fe08) in(0) from(0)
<= prom loc(<unknown>) prom(<unknown>=560af683fd28) in(0) from(0)
```

Then what the tracer is giving me right now is that there are two promises bound to `...`. 
From the trace we can figure out that `x=560af68427b8` and `y=560af6843528` are forced. We also know that promise `560af68427b8` is evaluated, but we don't know from the trace which variable in `...` that represents. Specifically, we aren't able to figure out from the trace whether `x=560af68427b8` or `v=560af68427b8` etc. 

This makes is hard to present that information in any sort of analysis of the trace. For instance, how do we represent the order of evaluation of promises?

I think the information about what is the name of the argument included in `...` is in the `...` SEXP somewhere, so we could easily fish it out. Then instead of saying:

```=> prom loc(<unknown>) prom(<unknown>=560af6842ac8) in(3) from(1)```

 we could say something like this:

```=> prom loc(<unknown>) prom(...[x]=560af6842ac8) in(3) from(1)```

**Comment by nohajc** [comment]
Fixed.
