### ISSUE TITLE
Make DB inserts faster

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#43]
Executing a sizable part of a  vignette for ggplot2 produced a trace of about 5-6mb which then takes about 12 minutes to insert into the DB. It may be worthwhile to see whether this can be lowered with prepared statements.

**Comment by kondziu** [comment]
Experiment (using ggplo2):

```
user     system    elapsed     method
16.696  44.156    820.897    uncompiled
12.260  45.056    908.788     compiled, 1-query per item (63bd11af0c7a0f78a3b7250c2491313dac7003f2)
 9.508  38.904    810.125     compiled, 1-query per all arguments/promises in call (a7a1220869f90e8b2700bb320700d342788aa46e￼)
```

Eh...

Loading from SQL takes:
```
real	13m1.285s
user	0m10.288s
sys	0m38.444s
```

**Comment by nohajc** [comment]
http://stackoverflow.com/questions/1711631/improve-insert-per-second-performance-of-sqlite

Take a look at this. Looks like the problem might be SQL transactions.

**Comment by kondziu** [comment]
Thanks! Yeah, I'll definitely check that out tomorrow, along with the other optimizations. (It definitely bothered me that it kept playing around with journal files for one.)

**Comment by fikovnik** [comment]
I wonder how long would this take by importing in sqlite from CSV using the import function?

**Comment by kondziu** [comment]
@fikovnik It's not a regular structure, so a single CSV would be a little weird.

**Comment by kondziu** [comment]
Progress!
```
user   system    elapsed     method
16.696  44.156    820.897    uncompiled
12.260  45.056    908.788    compiled, 1-query per item (63bd11af0c7a0f78a3b7250c2491313dac7003f2)
 9.508  38.904    810.125    compiled, 1-query per all arguments/promises in call (a7a1220869f90e8b2700bb320700d342788aa46e￼)
 1.392   0.012    1.526      compiled, everything in one transaction (c8ab3b6a0a1b6e48f23b14b6b4100a819e14c3f9)
```

Loading from SQL (one transaction)
```
real	0m0.093s
user	0m0.008s
sys	0m0.000s
```
Baseline:
```
real	13m1.285s
user	0m10.288s
sys	0m38.444s
```

**Comment by kondziu** [comment]
I think I'll close this with 4336a15760eb8e77bf230cdd953f655e280b7003
