### ISSUE TITLE
No-name functions in trace

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#48]
I get functions whose names are apparently zero-length strings (as opposed to NULLs). Where does that come from?

They showed up when executing the vignettes from "grid".

**Comment by kondziu** [comment]
Or did I mean promises not functions?

**Comment by nohajc** [comment]
The problem shows up with promises. I'm not sure if the same applies to functions. I hope not. :D

**Comment by kondziu** [comment]
Ok. So the problem is indeed in promise names. Example:
```
>> promise force name= id=16 in_call=0x14 from_call=0x14
<< promise force name= id=16 in_call=0x14 from_call=0x14
>> promise force name=<unknown> id=17 in_call=0x14 from_call=0x14
```

At the very least `name=` should also be `name=<unknown>`. I also don't know what a promise's name actually is, and maybe if I found out, then I could fill this out with more information, and maybe make this more legible.

**Comment by kondziu** [comment]
So apparently, an empty string is something that sometimes just appears there in the SEXP...
```
Breakpoint 3, recorder_t<compose<trace_recorder_t, sql_recorder_t> >::promise_get_info (rho=0x555556c1df50, symbol=0x555556c1e5a8, this=<optimized out>, this=<optimized out>) at rdt_promises/recorder.h:145
145	        const char *name = get_name(symbol);
(gdb) p (const char *)((SEXPREC_ALIGN *)(PRINTNAME(symbol)))+1
$13 = 0x555557088599 ""
```

**Comment by kondziu** [comment]
wut
```
(gdb) p info
$32 = {name = "expression", prom_id = -4, in_call_id = 0, from_call_id = 0}
>> promise force name=<unknown> id=-4 in_call=0x0 from_call=0x0
```

**Comment by kondziu** [comment]
goddamit...
