### ISSUE TITLE
Specials

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#49]
Special functions arbitrarily generate new function ids.

```
function_id		names	evaluations
"94466468888584"	"!="	"8"
"94466469104712"	"!="	"29"
"94466472791144"	"!="	"1"
"94466476807072"	"!="	"1"
"94466477068096"	"!="	"2"
"94466478133376"	"!="	"154"
"94466478245696"	"!="	"8"
"94466479549824"	"!="	"2"
"94466481739600"	"!="	"30"
"94466482644296"	"!="	"1"
"94466488715064"	"!="	"6"
"94466506674384"	"!="	"2"
```

**Comment by nohajc** [comment]
Um, doesn't R have something like operator overloading? I certainly heard you can redefine `if`. Perhaps the package redefines `!=`?

**Comment by kondziu** [comment]
Yeah it does. That's probably it. We should really start harvesting definitions for built-ins.

**Comment by kondziu** [comment]
I guess I should have closed this, as it looks like it's my mistake.
