### ISSUE TITLE
Open question: strinctness signatures of SPECIALSXPs

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#56]
This comes from a conversation with Aviral. Is there some way in which we can analyze how SPECIALSXPs use their "arguments" to create a model of their behavior for strictness analysis? In effect we would like to have strictness signatures like:

```
ifelse -> always -> sometimes -> sometimes
```

Telling us that the if always evaluates its condition (1st argument) and sometimes evaluates each of its two branches (second and third arguments).

Is this possible without delving into the source code of each individual SPECIALSXP?

**Comment by fikovnik** [comment]
We were talking about it. One way is static analysis of the underlying C code. I guess that should not be that difficult and I would like to try out the llvm static analysis framework for that. Another idea I had was to try to use RDT with gcov recording the basic blocks that were executed and then try to infer the patterns using some unsupervised learning. Given that specials are the basic functions we have a large pool of code to run so it might work.

**Comment by kondziu** [comment]
I guess the implicit assumption was that it'd need to be less effort than to model them manually though. For instance, I don't know if the phrases "not that difficult" and "static analysis of C code" can really be used together.

**Comment by fikovnik** [comment]
There are 38 specials, so probably doing it manually is the fastest way (although no fun). I do not have experience with LLVM, but this does not sound that hard, but maybe it is an overkill.

**Comment by nohajc** [comment]
I've worked with LLVM before, so I could probably investigate this. Is it LLVM though? I know you can work with C/C++ ASTs in clang but LLVM translates that into its internal representation. So, using LLVM, we would have to work on the IR level.

**Comment by fikovnik** [comment]
Well, there are actually:

```
|print_name   |c_entry         |offset     | eval|arity |pp_kind     |precedence  |rightassoc |  Z|  Y|  X|
|:------------|:---------------|:----------|----:|:-----|:-----------|:-----------|:----------|--:|--:|--:|
|if           |do_if           |0          |  200|-1    |PP_IF       |PREC_FN     |1          |  0|  0|  2|
|while        |do_while        |0          |  100|2     |PP_WHILE    |PREC_FN     |0          |  0|  0|  1|
|for          |do_for          |0          |  100|3     |PP_FOR      |PREC_FN     |0          |  0|  0|  1|
|repeat       |do_repeat       |0          |  100|1     |PP_REPEAT   |PREC_FN     |0          |  0|  0|  1|
|break        |do_break        |CTXT_BREAK |    0|0     |PP_BREAK    |PREC_FN     |0          |  0|  0|  0|
|next         |do_break        |CTXT_NEXT  |    0|0     |PP_NEXT     |PREC_FN     |0          |  0|  0|  0|
|return       |do_return       |0          |    0|-1    |PP_RETURN   |PREC_FN     |0          |  0|  0|  0|
|function     |do_function     |0          |    0|-1    |PP_FUNCTION |PREC_FN     |0          |  0|  0|  0|
|<-           |do_set          |1          |  100|-1    |PP_ASSIGN   |PREC_LEFT   |1          |  0|  0|  1|
|=            |do_set          |3          |  100|-1    |PP_ASSIGN   |PREC_EQ     |1          |  0|  0|  1|
|<<-          |do_set          |2          |  100|-1    |PP_ASSIGN2  |PREC_LEFT   |1          |  0|  0|  1|
|{            |do_begin        |0          |  200|-1    |PP_CURLY    |PREC_FN     |0          |  0|  0|  2|
|[            |do_subset       |1          |    0|-1    |PP_SUBSET   |PREC_SUBSET |0          |  0|  0|  0|
|[[           |do_subset2      |2          |    0|-1    |PP_SUBSET   |PREC_SUBSET |0          |  0|  0|  0|
|$            |do_subset3      |3          |    0|2     |PP_DOLLAR   |PREC_DOLLAR |0          |  0|  0|  0|
|@            |do_AT           |0          |    0|2     |PP_DOLLAR   |PREC_DOLLAR |0          |  0|  0|  0|
|[<-          |do_subassign    |0          |    0|3     |PP_SUBASS   |PREC_LEFT   |1          |  0|  0|  0|
|[[<-         |do_subassign2   |1          |    0|3     |PP_SUBASS   |PREC_LEFT   |1          |  0|  0|  0|
|$<-          |do_subassign3   |1          |    0|3     |PP_SUBASS   |PREC_LEFT   |1          |  0|  0|  0|
|switch       |do_switch       |0          |  200|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  2|
|.Internal    |do_internal     |0          |  200|1     |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  2|
|call         |do_call         |0          |    0|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|quote        |do_quote        |0          |    0|1     |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|substitute   |do_substitute   |0          |    0|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|missing      |do_missing      |1          |    0|1     |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|on.exit      |do_onexit       |0          |  100|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  1|
|forceAndCall |do_forceAndCall |0          |    0|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|Recall       |do_recall       |0          |  210|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  1|  2|
|&&           |do_logic2       |1          |    0|2     |PP_BINARY   |PREC_AND    |0          |  0|  0|  0|
|&#124;&#124; |do_logic2       |2          |    0|2     |PP_BINARY   |PREC_OR     |0          |  0|  0|  0|
|~            |do_tilde        |0          |    0|-1    |PP_BINARY   |PREC_TILDE  |0          |  0|  0|  0|
|@<-          |do_attrgets     |1          |    0|3     |PP_SUBASS   |PREC_LEFT   |1          |  0|  0|  0|
|cbind        |do_bind         |1          |   10|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  1|  0|
|rbind        |do_bind         |2          |   10|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  1|  0|
|round        |do_Math2        |10001      |    0|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|signif       |do_Math2        |10004      |    0|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|log          |do_log          |10003      |    0|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|withVisible  |do_withVisible  |1          |   10|1     |PP_FUNCALL  |PREC_FN     |0          |  0|  1|  0|
|expression   |do_expression   |1          |    0|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|rep          |do_rep          |0          |    0|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  0|
|eapply       |do_eapply       |0          |   10|4     |PP_FUNCALL  |PREC_FN     |0          |  0|  1|  0|
|lapply       |do_lapply       |0          |   10|2     |PP_FUNCALL  |PREC_FN     |0          |  0|  1|  0|
|vapply       |do_vapply       |0          |   10|4     |PP_FUNCALL  |PREC_FN     |0          |  0|  1|  0|
|UseMethod    |do_usemethod    |0          |  200|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  0|  2|
|NextMethod   |do_nextmethod   |0          |  210|-1    |PP_FUNCALL  |PREC_FN     |0          |  0|  1|  2|
```

here is the script:

```R
library(tidyverse)

names_c <- readLines("names.c")
funtab <- grep('^\\{".+\\},$', names_c, value=T)
funtab <- sub(",$", "", funtab)
funtab <- gsub("\t", "", funtab)

funtab <-
    read_csv(
        paste0(funtab, collapse="\n"),
        col_name=c("print_name", "c_entry", "offset", "eval", "arity", "pp_kind", "precedence", "rightassoc"),
        trim_ws=T,
        quote=NULL)

funtab %<>%
    mutate(
        print_name=substr(print_name, 3, nchar(print_name)-1),
        Z=eval %% 10,
        Y=(eval %/% 10) %% 10,
        X=(eval %/% 100) %% 10,
        pp_kind=substr(pp_kind, 2, nchar(pp_kind)),
        rightassoc=substr(rightassoc, 1, nchar(rightassoc)-2))

specials <- funtab %>% filter(Z==0)

specials %>% knitr::kable()
```

Another interesting part is the arity:

```
 specials %>% count(arity)
# A tibble: 6 × 2
  arity     n
  <chr> <int>
1    -1    25
2     0     2
3     1     5
4     2     6
5     3     5
6     4     2
```

There are 25 functions which can take arbitrary number of arguments.

**Comment by nohajc** [comment]
So... what is this script? I thought we were discussing clang/llvm.

**Comment by fikovnik** [comment]
@nohajc The script is just how I extracted which out the ~700 internal functions are specials based on their declaration. 

Isn't clang part of LLVM? A component that translates c code into the LLVM bitcode?

**Comment by nohajc** [comment]
@fikovnik Technically, clang is built on top of LLVM which is just a generic framework for writing frontends (clang being on of them).

It doesn't really matter though.

**Comment by fikovnik** [comment]
@nohajc And backends ;-)

I'll look into it and I will be asking you about LLVM! Thanks in advance :-)

**Comment by nohajc** [comment]
@fikovnik I hope I can help. I worked mainly with LLVM bitcode generation. Static analysis, not so much. Any general C++ questions are also welcome though. ;)

**Comment by aviralg** [comment]
When I initially talked to Filip, I also suggested the idea of static analysis. Now that we know there are only 38 SPECIALSXP, I feel that it is the wrong thing to do. Any such code will get complex fairly quickly so we need to have a convincing reason to do it. 38 SPECIALSXPs is not convincing enough for this. Moreover, without understanding the code of these specials, we can't design a static analysis. If we are understanding the code structure and implicit assumptions, we might as well manually write the signature down.

One argument in favor of automated static analysis is that if the implementation changes, then we can rerun the analysis. But then, if implementation is changed in such a way that the strictness signature changes, either:
1) The packages will break - this is something we should not care about because this means the developers are whimsical and don't care about consistency of the language semantics. In the end we have to target one particular R version anyways. 
2) The packages will not break, which means the packages are agnostic to the signature and hence we don't have to worry about which signature we choose.

**Comment by fikovnik** [comment]
Sounds reasonable. I create a file https://github.com/reactorlabs/strictr/blob/master/notes/specials.txt and filled in a few ones.

On the other hand, trying the analysis in LLVM is a good learning opportunity. I have some code from Tomas so I will play with it to get some knowledge about how it works.

@kondziu I think you can close this

**Comment by kondziu** [comment]
your wish is my command
