### ISSUE TITLE
Put your own configuration magic incantations on the wiki

### ISSUE THREAD

**Issue by licekto** [PRL-PRG/R-dyntrace#60]

**Comment by kondziu** [comment]
https://github.com/PRL-PRG/R-dyntrace/wiki/Configuration-and-building

done

**Comment by licekto** [comment]
arch linux build at the same place...

**Comment by kondziu** [comment]
Actually, we need @fikovnik's magical Mac incantation too.

**Comment by fikovnik** [comment]
Done
