### ISSUE TITLE
WTF prepared statements output

### ISSUE THREAD

**Issue by licekto** [PRL-PRG/R-dyntrace#65]
Specifics: Promise associations contain weird entries: `expr`, `names`, large negative values (pointers?). They should only call references to `promise_id`s, `call_id`s, `argument_id`s, which are all synthetically generated (small) integers.

**Comment by kondziu** [comment]
Large negative numbers are pointers from `functions.id`. Strings appear to be function names from `calls.function_name`.  Also there are many more promise_assocs generated by compiled statements than by file output SQL generator. The problem also does not occur when generating directly to DB from SQL strings without preparation.
