### ISSUE TITLE
Unhardcode compilation options: RDT_PROMISES_INDENT

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#7]
Move from #define to compilation options in makefile or to make dynamic and move to Rdt(...) -- whichever makes more sense.

**Comment by fikovnik** [comment]
The `Rdt()` option is easy to use. Basically you can do:

```r
Rdt(..., indent=4)
```

and then in the tracer, to get the value, simply:

```c
get_int(get_named_list_element(options, "indent"))
```
