### ISSUE TITLE
Documentation: document all of the C++ magic

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#72]
Describe the mechanisms you used in a lot of detail, so that an innocent bystander can figure out:

* what's going on
* why it's implemented that way
* how to make basic changes (add tracer, add recorder, add output etc.)

I figure after writing this up, let's have someone read it and modify accordingly too.

**Comment by fikovnik** [comment]
Perhaps also use this opportunity to review if all this magic is really necessary. The simpler the code the more chance the project won't rot so quickly. I understand that people like to show their C++ wizardry, but less is more :-)

**Comment by kondziu** [comment]
I think that's a separate issue. We need to document all this stuff so the knowledge doesn't disappear.
I think further re-factorization is sort of secondary, since we're fighting segfaults and we don't know if we can analyze all vignettes well. So I suggest making a separate issue so someone can handle that once we're done with the immediate mess.

**Comment by nohajc** [comment]
In my defense, I don't think it's wizardry. Apart from couple of macros (which I admit are complicated), it's just modern C++. I understand there's a higher learning curve but don't tell me you are unable to work on the project just because I use templates.

And the reason I use them (instead of runtime polymorphic virtual calls) is to make the hooks as fast as possible. It's code instrumentation after all and we don't want to slow down R any more than necessary.

**Comment by kondziu** [comment]
I like how templates are used. It makes sense to me and prevents having to write the same class multiple times.

I think the biggest bit of weirdness is the curiously recurring template pattern. It's really unintuitive as hell, but I think it's useful for what we're doing. If we get rid of it, we'll end up either copy-pasting a bunch of code or relying on run-time method dispatch, which I understand to be slow. 

I think personally I only have issues with some of the convenience macros like DECL_HOOK and to a lesser degree STATE, since they obfuscate the structure to me. It's not a big deal to me either though.

**Comment by nohajc** [comment]
@kondziu We can get rid of STATE if you want. It doesn't do anything particularly important.

I agree the DECL_HOOK machinery could be rewritten in a more simple (but ultimately more verbose to use) way.

CRTP is there to make recorder interface explicit. Without it, you can of course just use a generic type T and call methods on that, but then you lose the class hierarchy (and also IDE auto-completion :D). Furthermore, CRTP gives you the ability to have a method partially implemented in the base class and partially in the derived one. You have to tell the base class about your derived implementation (via the template parameter). Only then it can call methods on it.

If you compare this mechanism to classic virtual functions it's reversed. When you have a derived virtual method, you can call the parent class implementation in it. This wouldn't work for non-virtual calls, so instead we call from base to derived using static_cast.

(I guess I'll summarize these thoughts on the wiki too.)

**Comment by kondziu** [comment]
@nohajc Like I said, it's not that important to me. I'm willing to let it be. And I doubt whether those are what bother @fikovnik

**Comment by kondziu** [comment]
also @konrad =/= @kondziu ;)

**Comment by fikovnik** [comment]
@nohajc - you do not need to defend yourself :-) 

Modern C++ is fine, my only point was that things that can be simple shall remain simple. I only saw the macros for defining probe listeners and they are overkill. With the `calloc` you have the same verbosity, but way less code, no?

**Comment by nohajc** [comment]
@fikovnik Yeah, if this is about the probe listener registration, then I agree completely. It is an overkill. I can rewrite it, but I don't think it's a priority right now.

**Comment by kondziu** [comment]
We've limited the amount of C++ magic to the point where relationships are human readable.
