### ISSUE TITLE
Append timing info to R interface

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#75]
Time all executions of Rdt and print out the time info at the end of the execution to console.

**Comment by nohajc** [comment]
OK, do we stick this directly into the probe_end hook or should it be implemented as part of recorder?

I guess it could be a method of recorder_t shared between all the derived recorder classes. Or just hardcoded in the hook body. What do you think?

**Comment by kondziu** [comment]
I am thinking we do it in R.

**Comment by nohajc** [comment]
That makes sense. I haven't noticed the "R interface" part. :D

**Comment by kondziu** [comment]
Unless there are problems with that approach. But I think it will be easiest to do there, and it will work for all tracers always.
