### ISSUE TITLE
Open question: Move parts of the promise tracer into a separate package from RDT

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#79]
Do we want to do it? 
What would we want to move (just R, C+R?) 
Do we know how to do it...?

**Comment by fikovnik** [comment]
Yes!

We can have two projects - R-dyntrace - perhaps renamed to RDT? This one shall be in sync with R and contain the minimal changes to R to enable the traces. I guess we could have two remotes - a git-svn pointing to CRAN for R sources and one to github.

The promises related stuff will be in a package with a custom makefile.

**Comment by nohajc** [comment]
We could start by creating a branch where we disable the promise tracer entirely, so RDT can be compiled without all the ongoing C++ issues. After that we can figure out how to add promise tracer again but as a separate module.

**Comment by nohajc** [comment]
Also, the individual tracers don't necessarily have to be R packages. At least at first.

It's always just the question of calling the desired 'setup_*_tracing' from a shared library which can be a regular so/dylib.

In that case, we could only implement our own simple "plugin" registration, which would basically just `dlopen` the lib and called `dlsym` on the setup function.

Furthermore, if we adopt a convention that each tracer's library is called e.g. `librdt_tracername`, then we know what library to load and which function to call based on the tracer name itself.

**Comment by nohajc** [comment]
Anyway, I could start working on this.

**Comment by nohajc** [comment]
I created a new branch `rdt-core` and there's a version of R-dyntrace there which is compiled without our promises tracer. That has been moved into a separate project in `rdt-plugins` directory.

The separate project `promises` is build with cmake (works in CLion) and produces a shared library. 

That library is automatically loaded if you request the `promises` tracer. Specifically, it looks for a library named `librdt_promises` in a path given by an R variable `.RdtPlugins`.

See .Rprofile and src/library/rdt/src/dyn_fn_lookup.cpp

**Comment by nohajc** [comment]
OK, this is almost done. We just need to set the default tracer to something else than `promises` or not set any default at all.

I think the issue can be closed after that change. Unless we want the plugin tracers to be full-fledged R packages.

**Comment by kondziu** [comment]
I am not sure whether putting tracers into separate packages are a good idea or not, but we will probably do without them right now. I suggest closing the issue (and maybe opening another one for actual packages).
