### ISSUE TITLE
Take care of warnings.

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#8]
Just generally.

**Comment by nohajc** [comment]
The one remaining warning that shows up on my machine is about implicit declaration of "asprintf" which is a GNU extension of stdio.h and as such needs _GNU_SOURCE #defined in the source. That should be taken care of in config.h though. I tried changing order of includes to correctly propagate the macro definition but it still complained.

In any case, the function exists on Unix systems, so if we don't aim for portability, we can ignore this for now. Alternatively we can just replace asprintf with stringstream or something...
