### ISSUE TITLE
Build problem - undefined reference to `libintl*`

### ISSUE THREAD

**Issue by kalibera** [PRL-PRG/R-dyntrace#84]
I can't build R-dyntrace on my system (Ubuntu 16.04.2). Configure passes but the build fails with ../../lib/libR.so: undefined reference to `libintl_textdomain'. This is on a system where base R builds fine. Configured with "./configure --with-blas --with-lapack --enable-R-shlib"

```
gcc -Wl,--export-dynamic -fopenmp  -L../../lib -L/usr/local/lib -o R.bin Rmain.o  -lR 
../../lib/libR.so: undefined reference to `libintl_textdomain'
../../lib/libR.so: undefined reference to `libintl_bindtextdomain'
../../lib/libR.so: undefined reference to `libintl_gettext'
../../lib/libR.so: undefined reference to `libintl_ngettext'
../../lib/libR.so: undefined reference to `libintl_dgettext'
../../lib/libR.so: undefined reference to `libintl_dngettext'
collect2: error: ld returned 1 exit status
Makefile:142: recipe for target 'R.bin' failed
make[3]: *** [R.bin] Error 1
make[3]: Leaving directory '/home/tomas/work/git/R-dyntrace/src/main'
```

**Comment by kondziu** [comment]
I had the same problem. I think you're missing `--with-included-gettext`. Alternatively you need to install `libintl` dependencies.

Here's how we build: https://github.com/PRL-PRG/R-dyntrace/wiki/Configuration-and-building

**Comment by kalibera** [comment]
Thanks. When releasing this should really build like unpatched R.

**Comment by nohajc** [comment]
Yes, but we're not sure where the difference comes from. When I first started working on the project, it already required this config option. Does @fikovnik know something?

**Comment by fikovnik** [comment]
Nop, on my system it builds just fine without any extra configuration.

**Comment by kondziu** [comment]
Closed until further notice.
