### ISSUE TITLE
It is not clear which version of R is R-dyntrace based on

### ISSUE THREAD

**Issue by kalibera** [PRL-PRG/R-dyntrace#85]
I see that SVN-REVISION points to a much older version of R than the one patched currently. This should be fixed so that one can easily see what is changed compared to base R, so that one can have a look at the diff.

**Comment by kalibera** [comment]
It also might be worth updating to latest R-devel.

**Comment by kondziu** [comment]
What will be the benefit of updating to the latest R-devel? 

It sounds like it might be a lot of extra work (I personally don't even know where to start) so if it's about being up-to-date pro forma, I don't think it would be a priority.

**Comment by fikovnik** [comment]
I wonder why the `SVN-REVISION` is wrong. When I started I simply downloaded R sources from CRAN.

@kalibera - do you if there is any git mirror of the SVN? If not probably we could use git-svn to fetch the SVN sources.

**Comment by kalibera** [comment]
There is no official git mirror of the SVN. An unofficial one is at https://github.com/wch/r-source

**Comment by kondziu** [comment]
currently it's based on trunk, new SVN-REVISION is from trunk
