### ISSUE TITLE
Location of probes

### ISSUE THREAD

**Issue by kalibera** [PRL-PRG/R-dyntrace#87]
probe_function_entry, probe_function_exit - this should also be in execClosure. But if you update to latest R-devel, please note the code was refactored

eval.c:5616 - here is instrumented evaluation of arguments that will be passed into a builtin, but it is not the actual call to the builtin, which happens in other instructions

eval.c:5686 - missing instrumentation for a builtin call

eval.c:5692 - missing instrumentation for a special call
eval.c:1297 - missing instrumentation for a special call
eval.c:1313,1317 - missing instrumentation for a builtin call
eval.c:5750 - missing instrumentation for a special call
eval.c:6018 - missing instrumentation for a builtin call

I stopped here checking for missing instrumentation of builtin, special. Please look for PRIMFUN and instrument all calls that are around.

forcePromise - sometimes you only trace when a promise is really forced (expression evaluated), but sometimes you also trace when the value is looked up; please check that forcePromise function is called in both contexts and update the probe invocations accordingly (you'd probably need a branch and sometimes instrument as promise lookup rather than promise force)

objects.c:83 - missed instrumentation for promise lookup
also several cases in bind.c, and then I stopped looking
please grep from PRVALUE and instrument all calls

NOTE: R source location can be obtained using R_getCurrentSrcref (when source references are available); The current expression can be obtained via R_GlobalContext->call

I think the instrumentation for promise_unmarked is incorrect. TryToReleasePages is only run sometimes; this is a generational collector so we don't want to have to do a "sweep" through the whole heap every collection cycle. In this type of collector if you want to be sure you know when a promise has been reclaimed, you would have to do a full sweep yourself after marking. That would be slow, so you should rather register promises when they are created somehow - and so that you don't prevent collection, you could use weak references for this. (and there may be other issues instrumenting in TryToReleasePages - I am not sure if the type information is still available and why should it reliably not be next time - but I haven't read the code of the GC recently)

jump_ctxt - you do not instrument some long jumps, see all occurrences of "jumpctxt"; note that particularly you do not instrument long jumps due to errors, so it might be hard to interpret traces when an R function f1 results in an error and then f2 is called vs when f1 calls f2; yet this probably depends on a usecase... I can speculate users may want to know if a function exited normally or due to an error (yet indeed you instrument Rf_error*)... Note though "return" is also often a long jump. And that the return may be wrapped in a promise, so one may be returning from a function that is not the latest function entered (this is e.g. used in exception handling code; not sure if you want to capture this)

**Comment by nohajc** [comment]
> you should rather register promises when they are created somehow

Can you elaborate? It would be simple to register promises but I don't see how that alone solves the problem of being notified when they are garbage collected. 

Anyway, I used this hook only for optimizing memory consumption. We have a map `promise_ids` from addresses to our generated IDs and it would be nice to clear it from time to time. Otherwise it should work even without the gc hook. Every time a new promise is created on a previously used address, we just generate a new ID and update the corresponding record in the map.

**Comment by nohajc** [comment]
@kalibera Can you give a minimal example of R code where return gets wrapped in a promise?

**Comment by kalibera** [comment]
Have a look at implementation of `tryCatch`, it is useful to read and understand its code. `return` is passed as argument in `doTryCatch(return(expr)...`. A smaller but contrived example:

```
> f <- function() { g(return(2)) ; return(1) }
> g <- function(x) x
> f()
[1] 2
```

**Comment by nohajc** [comment]
OK, return wrapped in a promise works and we only need the jump_ctxt hook for exceptions, so maybe we can rename it. 

Otherwise I addressed all the issues above. Closing.
