### ISSUE TITLE
Fix make to properly compile/link header files

### ISSUE THREAD

**Issue by kondziu** [PRL-PRG/R-dyntrace#92]
Right now you need to `make clean` whenever modifying headers. If you forget to do it you get memory weirdness. I'm tired of getting memory weirdness, guys D:

**Comment by nohajc** [comment]
I don't know why this happens. I checked the Makefile and while there aren't header files mentioned explicitly, there's a rule to generate dependencies for each c/cpp file. Dependencies are the header files so it should work.
