### ISSUE TITLE
Indentation broken again

### ISSUE THREAD

**Issue by nohajc** [PRL-PRG/R-dyntrace#97]
When tracing `testEx1` function from the example set, the indentation does not add up.

There are now many promise lookups which we have not seen before (due to added instrumentation) couldn't that break something?

**Comment by kondziu** [comment]
I traced testEx1. I don't really see it...?
[trace.txt](https://github.com/PRL-PRG/R-dyntrace/files/959267/trace.txt)

**Comment by nohajc** [comment]
Well, line 1555 should have zero indentation.

**Comment by kondziu** [comment]
yeah, ok

it's at 32, so i guess there are at least 8 instances of a missing unindent

**Comment by nohajc** [comment]
OK, I just realized it's probably caused by promise force indentation. While we handle function unwinding, we don't handle promise unwinding. When we happen to throw an exception from a nested promise evaluation, the indentation level isn't decremented properly (cause we skip promise force exits).

It's just a theory but I can try to verify my suspicion tomorrow.
